import './globals.css'
import { Header } from './componments/Header/Header'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-gray-700'>
        <Header/>
        {children}
        </body>
    </html>
  )
}
